### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [2]:
a = np.array([1,2,3], dtype='int8')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]], dtype='int16')
print(b)

[[9 8 7]
 [6 5 4]]


In [4]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Get Shape
a.shape

(3,)

In [6]:
b.shape

(2, 3)

In [7]:
# Get Type
a.dtype

dtype('int8')

In [8]:
# Get Size
a.itemsize

1

In [9]:
b.itemsize

2

In [10]:
# Get total size
a.nbytes

3

In [11]:
b.nbytes

12

In [12]:
# Get number of elements
a.size

3

In [13]:
b.size

6

### Accessing/Changing specific elements, rows, columns, etc

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]], dtype='int16')
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# Get a specific element [r, c]
a[1, 4]

12

In [16]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7], dtype=int16)

In [17]:
# Get a specific column
a[:, 2]

array([ 3, 10], dtype=int16)

In [18]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[1, 1::2]

array([ 9, 11, 13], dtype=int16)

In [19]:
a[1,5] = 20

a[:,2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [20]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# Get specific element (work outside in)
b[0,1,1]

4

In [22]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [23]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [24]:
np.zeros(2, dtype='int8')

array([0, 0], dtype=int8)

In [25]:
# All 0s matrix
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
# All 1s matrix
np.ones((4,2,2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [27]:
# Any other number
np.full((2, 2, 3), 99, dtype='int16')

array([[[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]]], dtype=int16)

In [28]:
# Any other number (full_like)
np.full_like(b, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [29]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.90816567, 0.31047827],
       [0.0564196 , 0.44680064],
       [0.8156378 , 0.56367308],
       [0.41044786, 0.19920711]])

In [30]:
# Random Integer values
np.random.randint(-2, 4, size=(3, 3))

array([[ 0,  2,  2],
       [ 3,  1,  3],
       [ 0, -2, -1]])

In [31]:
# The identity matrix
np.identity(5, dtype='int8')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [32]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [33]:
# Repeat an array
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [34]:
output = np.ones((5,5), dtype='int8')
print(output)

z = np.zeros((3,3), dtype='int8')
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


##### Be careful when copying arrays!!!

In [35]:
a = np.array([1,2,3])
b = a.copy() # use .copy()
b[0] = 100

print(a)

[1 2 3]


In [36]:
print(b)

[100   2   3]


### Mathematics

In [37]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [38]:
a + 2

array([3, 4, 5, 6])

In [39]:
a - 2

array([-1,  0,  1,  2])

In [40]:
a * 2

array([2, 4, 6, 8])

In [41]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [42]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [43]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [44]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [45]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [46]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [47]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

### Determinant
### Trace
### Singular Vector Decomposition
### Eigenvalues
### Matrix Norm
### Inverse
### Etc...

##### Statistics

In [48]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.min(stats)

1

In [50]:
np.max(stats, axis=0)

array([4, 5, 6])

In [51]:
np.sum(stats)

21

In [52]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [53]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print("\n")
after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [54]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
# Horizontal  stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [57]:
filedata = np.genfromtxt('data.txt', delimiter=',').astype('int16')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking and Advanced Indexing

In [58]:
(filedata > 5) & (filedata < 15)

array([[False,  True, False,  True, False, False, False, False, False,
         True,  True,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False,  True,
        False, False, False, False,  True,  True, False,  True,  True],
       [False, False, False,  True, False,  True, False, False, False,
        False, False, False,  True,  True,  True, False, False, False]])

In [59]:
filedata[filedata > 10]

array([ 13,  21,  11, 196,  75,  34,  42,  12,  33, 766,  75,  55,  11,
        12,  22,  33,  11, 999,  11,  78,  76,  88], dtype=int16)

In [60]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])